### PR TITLE
WIP: Implement First Unit Testing

### PR DESCRIPTION
**Pull request by rickbau5**
This will be a **WIP** for a while. Setting up unit testing for the project. This will really help confirm changes have the intended results and don't have any unexpected side effects. 

Gradle was added to manage the JUnit5 dependency. Tests can be run within Eclipse/IntelliJ (google for instructions), or from the command line:
``` bash
# Mac/Linux
./gradlew clean test
# Windows
gradlew.bat clean test # untested but should work.
```
I'll add documentation at a later time. 

- Restructure project layout
- Add gradle for dependency management
- Add JUnit5 as project dependency for testing
- Implement first unit tests.

### CODE REVIEW

**Comment by Vrekt** [comment]
Cool thank you, when I get home later Ill set everything up and get back to working on some things.

**Comment by Vrekt** [comment]
I also wanted to change the package name of the project since multiple people are contributing to it. But I'm not sure if it will break things? I was just thinking the package name 'lunar'. 
So like:
lunar.world.World
lunar.entity
etc, etc

Will it break anything or is it safe to change the names and push?

**Comment by rickbau5** [comment]
Here's the [standard naming conventions spec](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). I'd suggest something like `com.lunar`.

Resulting in
```
com.lunar.world.World
com.lunar.entity
```

EDIT: It's not really necessary that the domain `www.lunar.com` exists and is related to this project - it's just the convention.

EDIT EDIT: [it does exist](http://www.lunar.com/)

**Comment by Vrekt** [comment]
Alright, I'll probably either use com.lunar or just me.lunar, or whatever you suggest

**Pull request merged**
