### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by Vrekt**

### CODE REVIEW

**Comment by Vrekt** [comment]
@rickbau5 honestly have no idea how to fix this conflict. Could you help me out a bit?

**Comment by rickbau5** [comment]
I’m out of the country till end of next week, I can get it resolved then

**Comment by Vrekt** [comment]
@rickbau5 alright, I'm still learning so i already messed something up but Ill resolve it.

**Comment by rickbau5** [comment]
Ooh wait yeah that commit you just made has all the changes from the other branch you just merged in. Just leave this branch be and I’ll get it I’m working order 👍🏼 Turns out I actually have it on this computer I’ve got

**Comment by Vrekt** [comment]
@rickbau5 oh okay thank you!

**Pull request closed without merging**
